<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <TargetFramework>net4.8</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Exiled</Configurations>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <Platforms>x64</Platforms>
    <ReferencesPath Condition="'$(ReferencesPath)' == ''">..\..\packages\Exiled.Dev.References.1.0.4\lib\net48</ReferencesPath>
    <ExModPath>..\..\packages\ExMod.Exiled.9.14.2\lib\net48</ExModPath>
    <MirrorPath Condition="'$(MirrorPath)' == '' and Exists('$(ReferencesPath)\Mirror_publicized.dll')">$(ReferencesPath)\Mirror_publicized.dll</MirrorPath>
    <MirrorPath Condition="'$(MirrorPath)' == ''">$(ReferencesPath)\Mirror.dll</MirrorPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Exiled|x64' ">
    <Optimize>true</Optimize>
    <DefineConstants>EXILED,TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\packages\ExMod.Exiled.9.14.2\lib\net48\Assembly-CSharp-Publicized.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(ReferencesPath)\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath Condition="Exists('$(ReferencesPath)\CommandSystem.Core.dll')">$(ReferencesPath)\CommandSystem.Core.dll</HintPath>
      <HintPath Condition="!Exists('$(ReferencesPath)\CommandSystem.Core.dll')">$(ExModPath)\CommandSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.API" Condition=" '$(Configuration)|$(Platform)' == 'Exiled|x64' ">
      <HintPath>..\..\packages\ExMod.Exiled.9.14.2\lib\net48\Exiled.API.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CustomItems" Condition=" '$(Configuration)|$(Platform)' == 'Exiled|x64' ">
      <HintPath>..\..\packages\ExMod.Exiled.9.14.2\lib\net48\Exiled.CustomItems.dll</HintPath>
    </Reference>
    <Reference Include="LabApi">
      <HintPath>..\..\packages\ExMod.Exiled.9.14.2\lib\net48\LabApi.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(MirrorPath)</HintPath>
    </Reference>
    <Reference Include="mscorlib">
      <HintPath>$(ReferencesPath)\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="NorthwoodLib">
      <HintPath Condition="Exists('$(ReferencesPath)\NorthwoodLib.dll')">$(ReferencesPath)\NorthwoodLib.dll</HintPath>
      <HintPath Condition="!Exists('$(ReferencesPath)\NorthwoodLib.dll')">$(ExModPath)\NorthwoodLib.dll</HintPath>
    </Reference>
    <Reference Include="Pooling">
      <HintPath>$(ReferencesPath)\Pooling.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <HintPath>$(ReferencesPath)\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(ReferencesPath)\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ReferencesPath)\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ReferencesPath)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(ReferencesPath)\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(ReferencesPath)\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ReferencesPath)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ReferencesPath)\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath Condition="Exists('$(ReferencesPath)\YamlDotNet.dll')">$(ReferencesPath)\YamlDotNet.dll</HintPath>
      <HintPath Condition="!Exists('$(ReferencesPath)\YamlDotNet.dll')">$(ExModPath)\YamlDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
  </ItemGroup>

</Project>
